import type { Metadata } from "next";
import SeoArticle from "../_components/SeoArticle";
const path="/blog/cach-can-bang-phuong-trinh-hoa-hoc"; const title="Cách cân bằng phương trình hóa học: quy trình 4 bước"; const description="Cách cân bằng phương trình hóa học an toàn là đếm nguyên tử, chọn chất phù hợp để đặt hệ số, cân bằng H và O sau cùng, rồi kiểm tra và rút gọn.";
export const metadata:Metadata={title,description,alternates:{canonical:path},openGraph:{title,description,url:path,type:"article"}};
const faqs=[{question:"Cân bằng phương trình có được sửa chỉ số không?",answer:"Không. Sửa chỉ số làm thay đổi công thức và có thể tạo thành chất khác. Chỉ được đặt hệ số ở trước công thức."},{question:"Nên cân bằng nguyên tố nào trước?",answer:"Thường ưu tiên nguyên tố xuất hiện trong ít chất hơn hoặc nhóm nguyên tử được giữ nguyên ở hai vế. H và O thường để sau, nhưng đây là chiến lược chứ không phải luật tuyệt đối."},{question:"Hệ số 1 có cần viết không?",answer:"Không cần viết hệ số 1. Ví dụ 2H₂ + O₂ → 2H₂O được hiểu O₂ có hệ số 1."},{question:"Làm sao biết phương trình đã tối giản?",answer:"Kiểm tra số nguyên tử hai vế bằng nhau, sau đó xem các hệ số có cùng chia được cho một số nguyên lớn hơn 1 hay không."}];
export default function Page(){return <SeoArticle title={title} description={description} path={path} image="/infographic-hoa-co-ban.jpg" imageAlt="Bốn bước cân bằng phương trình Fe tác dụng với oxygen tạo Fe₂O₃" kicker="HÓA THCS · PHƯƠNG TRÌNH" readingTime="9 phút đọc" quickAnswer={<p>Để cân bằng phương trình hóa học, em chỉ thay đổi hệ số đứng trước công thức, tuyệt đối không sửa chỉ số. Hãy đếm nguyên tử hai vế, cân bằng nguyên tố phù hợp trước, để H và O về sau khi thuận tiện, rồi kiểm tra tất cả nguyên tố và rút gọn hệ số.</p>} summary={["Không thay đổi chỉ số trong công thức.","Đếm nguyên tử trước khi đoán hệ số.","Ưu tiên nguyên tố xuất hiện ít vị trí.","Kiểm tra lại toàn bộ hai vế.","Rút gọn về tỉ lệ số nguyên nhỏ nhất."]} toc={[{id:"ban-chat",label:"Bản chất của cân bằng"},{id:"bon-buoc",label:"Quy trình 4 bước"},{id:"vi-du",label:"Ví dụ giải từng bước"},{id:"loi-sai",label:"Lỗi thường gặp"},{id:"bai-tap",label:"Bài tập tự kiểm tra"}]} faqs={faqs} links={[{href:"/blog/mat-goc-hoa-nen-bat-dau-tu-dau",label:"lộ trình học lại Hóa từng bước"},{href:"/blog/checklist-kien-thuc-hoa-thcs",label:"checklist kiến thức Hóa THCS"},{href:"/blog/bai-toan-nong-do-dung-dich",label:"bài toán nồng độ dung dịch"}]} cta={{title:"Muốn luyện bằng phản hồi tức thì?",text:"Mở công cụ Lấy gốc hóa để ôn công thức, phản ứng và làm câu hỏi tương tác.",href:"/lay-goc-hoa.html",label:"Mở công cụ Lấy gốc hóa"}}>
<section><h2 id="ban-chat">Vì sao phải cân bằng?</h2><p>Trong phản ứng hóa học, các nguyên tử được sắp xếp lại chứ không tự sinh ra hoặc mất đi. Vì vậy, số nguyên tử của mỗi nguyên tố ở vế chất tham gia phải bằng số nguyên tử của nguyên tố đó ở vế sản phẩm.</p><p>Hệ số nhân với toàn bộ công thức. Trong 2H₂O có 4 nguyên tử H và 2 nguyên tử O. Chỉ số 2 trong H₂O thuộc về công thức của chất; thay nó sẽ làm công thức thay đổi.</p></section>
<section><h2 id="bon-buoc">Quy trình cân bằng phương trình hóa học 4 bước</h2><ol><li><strong>Viết đúng công thức</strong> của chất tham gia và sản phẩm.</li><li><strong>Đếm nguyên tử</strong> mỗi nguyên tố ở hai vế.</li><li><strong>Đặt hệ số</strong> để cân bằng, ưu tiên nguyên tố xuất hiện ở ít chất; để H, O sau nếu thuận tiện.</li><li><strong>Kiểm tra và rút gọn</strong> tất cả hệ số về số nguyên nhỏ nhất.</li></ol></section>
<section><h2 id="vi-du">Ví dụ: Fe + O₂ → Fe₂O₃</h2><ol><li>O ở trái đi theo nhóm 2, ở phải đi theo nhóm 3. Bội chung nhỏ nhất là 6.</li><li>Đặt 3 trước O₂ và 2 trước Fe₂O₃: Fe + 3O₂ → 2Fe₂O₃.</li><li>Vế phải có 4 Fe, nên đặt 4 trước Fe.</li><li>Kết quả: <strong>4Fe + 3O₂ → 2Fe₂O₃</strong>.</li></ol><table><thead><tr><th>Nguyên tố</th><th>Vế trái</th><th>Vế phải</th></tr></thead><tbody><tr><td>Fe</td><td>4</td><td>2 × 2 = 4</td></tr><tr><td>O</td><td>3 × 2 = 6</td><td>2 × 3 = 6</td></tr></tbody></table><h3>Ví dụ có nhóm nguyên tử giữ nguyên</h3><p>Al + CuSO₄ → Al₂(SO₄)₃ + Cu. Xem SO₄ như một nhóm: đặt 3 trước CuSO₄, 2 trước Al và 3 trước Cu. Kết quả: <strong>2Al + 3CuSO₄ → Al₂(SO₄)₃ + 3Cu</strong>.</p></section>
<section><h2 id="loi-sai">Bốn lỗi thường gặp</h2><ul><li><strong>Sửa chỉ số:</strong> đổi O₂ thành O₃. Cách sửa: chỉ đặt số ở trước công thức.</li><li><strong>Quên hệ số nhân toàn công thức:</strong> 2H₂O có 2 O, không phải 1 O.</li><li><strong>Dừng khi mới cân bằng một nguyên tố:</strong> luôn kiểm tra tất cả nguyên tố.</li><li><strong>Không rút gọn:</strong> 4H₂ + 2O₂ → 4H₂O cần chia các hệ số cho 2.</li></ul></section>
<section><h2 id="bai-tap">Tự kiểm tra</h2><ol><li>__Mg + __O₂ → __MgO</li><li>__H₂ + __O₂ → __H₂O</li><li>__Al + __HCl → __AlCl₃ + __H₂</li><li>Đúng hay sai: có thể sửa H₂O thành H₂O₂ khi cân bằng?</li></ol><details><summary>Xem đáp án</summary><p>1. 2Mg + O₂ → 2MgO. 2. 2H₂ + O₂ → 2H₂O. 3. 2Al + 6HCl → 2AlCl₃ + 3H₂. 4. Sai, vì H₂O₂ là chất khác.</p></details></section>
<section><h2>Kết luận</h2><p>Cân bằng không phải trò đoán số. Khi viết đúng chất, đếm nguyên tử, đặt hệ số có chiến lược và kiểm tra lại, em sẽ giảm rõ rệt lỗi sửa chỉ số hoặc bỏ sót nguyên tố.</p></section>
</SeoArticle>}
