import type { Metadata } from "next";
import SeoArticle from "../_components/SeoArticle";
const path="/blog/checklist-kien-thuc-hoa-thcs"; const title="Checklist kiến thức Hóa THCS cần vững trước khi học lớp 10"; const description="Checklist kiến thức Hóa THCS giúp học sinh lớp 9–10 rà soát các mắt xích quan trọng: công thức, hóa trị, phương trình, mol, dung dịch và hợp chất vô cơ.";
export const metadata:Metadata={title,description,alternates:{canonical:path},openGraph:{title,description,url:path,type:"article"}};
const faqs=[{question:"Có cần thuộc toàn bộ bảng tuần hoàn trước lớp 10 không?",answer:"Không. Em cần đọc được kí hiệu, hiểu số hiệu nguyên tử ở mức đã học và quen các nguyên tố thường gặp; không cần học thuộc toàn bộ bảng."},{question:"Phần nào quan trọng nhất trước khi học Hóa 10?",answer:"Không có một phần duy nhất, nhưng công thức hóa học, hóa trị và phương trình là các mắt xích sớm. Nếu các phần này hổng, bài định lượng sau đó sẽ khó hơn."},{question:"Checklist này có thay thế sách giáo khoa không?",answer:"Không. Đây là bản đồ rà soát. Nội dung và thuật ngữ chi tiết cần đối chiếu bộ sách và yêu cầu của giáo viên tại trường."}];
export default function Page(){return <SeoArticle title={title} description={description} path={path} image="/infographic-hoa-co-ban.jpg" imageAlt="Infographic tổng hợp kiến thức nền Hóa THCS trước lớp 10" kicker="PILLAR KIẾN THỨC NỀN" readingTime="9 phút đọc" quickAnswer={<p>Trước lớp 10, em không cần học trước thật nhiều nội dung mới. Điều quan trọng là đọc đúng kí hiệu và công thức, dùng được hóa trị, hiểu phản ứng, cân bằng phương trình, đổi được mol–khối lượng và phân biệt các đại lượng dung dịch cơ bản.</p>} summary={["Rà soát theo năng lực làm được, không theo cảm giác đã học.","Đánh dấu Vững / Mơ hồ / Chưa biết cho từng mục.","Ưu tiên công thức và phương trình trước bài toán.","Mỗi mục phải có một ví dụ tự làm.","Kiểm tra lại sau khi học, không chỉ đọc lại."]} toc={[{id:"ngon-ngu",label:"Ngôn ngữ Hóa học"},{id:"phan-ung",label:"Phản ứng và phương trình"},{id:"dinh-luong",label:"Mol và dung dịch"},{id:"hop-chat",label:"Hợp chất vô cơ"},{id:"cach-dung",label:"Cách dùng checklist"}]} faqs={faqs} links={[{href:"/blog/mat-goc-hoa-nen-bat-dau-tu-dau",label:"lộ trình học lại Hóa từng bước"},{href:"/blog/bai-kiem-tra-chan-doan-mat-goc-hoa",label:"bài kiểm tra chẩn đoán mất gốc Hóa"},{href:"/blog/cach-can-bang-phuong-trinh-hoa-hoc",label:"quy trình cân bằng phương trình hóa học"}]} cta={{title:"Biến checklist thành kết quả cụ thể",text:"Làm 12 câu chẩn đoán để xác định mục nào đang vững, mơ hồ hoặc cần học lại.",href:"/blog/bai-kiem-tra-chan-doan-mat-goc-hoa",label:"Làm bài chẩn đoán"}}>
<section><h2 id="ngon-ngu">1. Ngôn ngữ Hóa học</h2><ul><li>□ Đọc đúng kí hiệu của các nguyên tố thường gặp.</li><li>□ Phân biệt nguyên tử, nguyên tố và phân tử.</li><li>□ Phân biệt đơn chất với hợp chất từ công thức.</li><li>□ Hiểu chỉ số cho biết số nguyên tử trong một công thức.</li><li>□ Tính được phân tử khối/khối lượng mol từ dữ liệu cho trước.</li><li>□ Dùng quy tắc hóa trị để lập công thức đơn giản.</li></ul><div className="tip"><strong>Tự kiểm tra:</strong> giải thích vì sao công thức aluminium oxide là Al₂O₃, không phải AlO.</div></section>
<section><h2 id="phan-ung">2. Phản ứng và phương trình</h2><ul><li>□ Nhận ra chất tham gia và sản phẩm.</li><li>□ Phân biệt hiện tượng vật lí và biến đổi hóa học ở mức cơ bản.</li><li>□ Viết sơ đồ chữ hoặc công thức khi đã biết chất.</li><li>□ Cân bằng bằng hệ số, không sửa chỉ số.</li><li>□ Kiểm tra lại số nguyên tử mỗi nguyên tố ở hai vế.</li></ul><p>Ví dụ chuẩn: 4Fe + 3O₂ → 2Fe₂O₃. Hai vế đều có 4 nguyên tử Fe và 6 nguyên tử O.</p></section>
<section><h2 id="dinh-luong">3. Mol, khối lượng và dung dịch</h2><ul><li>□ Hiểu mol là đơn vị lượng chất.</li><li>□ Dùng n = m/M và m = nM đúng đại lượng, đơn vị.</li><li>□ Đổi mL sang L trước khi dùng công thức có thể tích tính bằng lít.</li><li>□ Phân biệt chất tan, dung môi và dung dịch.</li><li>□ Tính C% = m chất tan / m dung dịch × 100%.</li><li>□ Dùng C<sub>M</sub> = n/V khi V tính bằng lít.</li></ul></section>
<section><h2 id="hop-chat">4. Oxit, axit, bazơ và muối</h2><table><thead><tr><th>Nhóm</th><th>Dấu hiệu công thức cơ bản</th><th>Ví dụ</th></tr></thead><tbody><tr><td>Oxit</td><td>Hai nguyên tố, một là oxygen</td><td>CaO, CO₂</td></tr><tr><td>Axit</td><td>Thường có H đứng đầu trong phạm vi cơ bản</td><td>HCl, H₂SO₄</td></tr><tr><td>Bazơ</td><td>Kim loại và nhóm OH</td><td>NaOH, Ca(OH)₂</td></tr><tr><td>Muối</td><td>Cation kim loại/NH₄⁺ và gốc axit</td><td>NaCl, CuSO₄</td></tr></tbody></table><p>Đây là dấu hiệu nhận biết cơ bản, không thay thế định nghĩa và các ngoại lệ sẽ học ở mức cao hơn.</p></section>
<section><h2 id="cach-dung">5. Cách dùng checklist trong 30 phút</h2><ol><li>Đánh dấu bằng ví dụ thật: chỉ chọn “vững” nếu tự làm được.</li><li>Khoanh mục “chưa biết” xuất hiện sớm nhất.</li><li>Học một bài và làm 3–5 câu cơ bản.</li><li>Ghi lỗi sai bằng một câu.</li><li>Kiểm tra lại sau vài ngày bằng câu khác.</li></ol><h3>Ba lỗi cần tránh</h3><ul><li>Đánh dấu “đã học” thay cho “đã làm được”.</li><li>Ôn tất cả mục cùng lúc.</li><li>Chỉ xem video mà không tự viết công thức và phép tính.</li></ul></section><section><h2>Kết luận</h2><p>Checklist là bản đồ, không phải đích đến. Sau khi khoanh được lỗ hổng, em cần biến từng mục thành một hành động: học lại, làm ví dụ, chữa lỗi và kiểm tra lại.</p></section>
</SeoArticle>}
