import type { Metadata } from "next";
import SeoArticle from "../_components/SeoArticle";
const path="/blog/bai-kiem-tra-chan-doan-mat-goc-hoa"; const title="Bài kiểm tra chẩn đoán mất gốc Hóa: 6 nhóm kiến thức"; const description="Bài kiểm tra chẩn đoán mất gốc Hóa giúp em xác định lỗ hổng theo 6 nhóm, thay vì chỉ nhận một điểm tổng và không biết nên học lại phần nào.";
export const metadata:Metadata={title,description,alternates:{canonical:path},openGraph:{title,description,url:path,type:"article"}};
const faqs=[{question:"Bài test mất gốc Hóa cần làm bao lâu?",answer:"Khoảng 15–20 phút là đủ cho một vòng sàng lọc cơ bản. Mục tiêu là tìm nhóm cần học lại, không phải mô phỏng một bài thi."},{question:"Điểm thấp có nghĩa là em phải học lại tất cả không?",answer:"Không. Hãy xem từng nhóm câu hỏi. Em có thể chỉ hổng một mắt xích khiến các phần sau cùng sai."},{question:"Có nên xem công thức khi làm bài chẩn đoán?",answer:"Lượt đầu không nên xem để phản ánh khả năng hiện tại. Sau đó em có thể làm lại có tài liệu để phân biệt lỗi nhớ kiến thức và lỗi hiểu cách làm."}];
export default function Page(){return <SeoArticle title={title} description={description} path={path} image="/phieu-nhan-xet-buoi-hoc.jpg" imageAlt="Phiếu chẩn đoán sáu nhóm kiến thức nền Hóa học" kicker="CÔNG CỤ TỰ KIỂM TRA" readingTime="8 phút đọc" quickAnswer={<p>Một bài chẩn đoán tốt không chỉ báo đúng hoặc sai. Nó phân loại lỗi theo nhóm: ngôn ngữ Hóa học, hóa trị, phản ứng, phương trình, mol và dung dịch. Sau khi làm, em chọn nhóm sai sớm nhất trong chuỗi để học lại trước.</p>} summary={["Làm không dùng tài liệu trong 15–20 phút.","Chấm theo từng nhóm, không chỉ nhìn tổng điểm.","Ghi nguyên nhân sai: quên, hiểu nhầm hay tính nhầm.","Học lại mắt xích sai sớm nhất.","Làm lại câu tương đương sau 3–7 ngày."]} toc={[{id:"cach-lam",label:"Cách làm bài"},{id:"cau-hoi",label:"12 câu chẩn đoán"},{id:"cham",label:"Đáp án và cách đọc kết quả"},{id:"sau-test",label:"Việc cần làm sau bài test"}]} faqs={faqs} links={[{href:"/blog/mat-goc-hoa-nen-bat-dau-tu-dau",label:"mất gốc Hóa nên bắt đầu từ đâu"},{href:"/blog/checklist-kien-thuc-hoa-thcs",label:"checklist kiến thức Hóa THCS"},{href:"/lay-goc-hoa.html",label:"công cụ Lấy gốc hóa tương tác"}]} cta={{title:"Muốn luyện thêm bằng công cụ tương tác?",text:"Mở trang Lấy gốc hóa để dùng bảng tuần hoàn, công thức, mô phỏng và câu hỏi luyện tập.",href:"/lay-goc-hoa.html",label:"Mở công cụ Lấy gốc hóa"}}>
<section><h2 id="cach-lam">Cách làm để kết quả có ý nghĩa</h2><ol><li>Chuẩn bị giấy nháp, không mở bảng hóa trị ở lượt đầu.</li><li>Đặt thời gian tối đa 20 phút.</li><li>Bên cạnh mỗi câu sai, ghi K nếu quên kiến thức, H nếu chưa hiểu, T nếu tính nhầm.</li><li>Chỉ xem đáp án sau khi hoàn thành cả 12 câu.</li></ol></section>
<section><h2 id="cau-hoi">12 câu chẩn đoán</h2><h3>Nhóm A — Ngôn ngữ Hóa học</h3><ol><li>Trong 3H₂O, hệ số và chỉ số lần lượt là số nào?</li><li>Phân loại O₂ và CO₂ thành đơn chất hoặc hợp chất.</li></ol><h3>Nhóm B — Hóa trị và công thức</h3><ol start={3}><li>Biết Al hóa trị III và O hóa trị II, viết công thức aluminium oxide.</li><li>Trong Fe₂O₃, Fe có hóa trị bao nhiêu?</li></ol><h3>Nhóm C — Phản ứng và phương trình</h3><ol start={5}><li>Trong Mg + O₂ → MgO, đâu là chất phản ứng?</li><li>Cân bằng: Fe + O₂ → Fe₂O₃.</li></ol><h3>Nhóm D — Mol và khối lượng</h3><ol start={7}><li>Tính số mol của 18 g H₂O, biết M(H₂O) = 18 g/mol.</li><li>0,5 mol CO₂ có khối lượng bao nhiêu? M(CO₂) = 44 g/mol.</li></ol><h3>Nhóm E — Dung dịch</h3><ol start={9}><li>Hòa tan 10 g muối vào 90 g nước. Khối lượng dung dịch là bao nhiêu?</li><li>Dung dịch trên có nồng độ phần trăm bao nhiêu?</li></ol><h3>Nhóm F — Đọc đề và đơn vị</h3><ol start={11}><li>250 mL bằng bao nhiêu lít?</li><li>Trong công thức C<sub>M</sub> = n/V, V phải dùng đơn vị nào?</li></ol></section>
<section><h2 id="cham">Đáp án và cách đọc kết quả</h2><details><summary>Xem đáp án</summary><p>1. Hệ số 3, chỉ số 2. 2. O₂ là đơn chất; CO₂ là hợp chất. 3. Al₂O₃. 4. III. 5. Mg và O₂. 6. 4Fe + 3O₂ → 2Fe₂O₃. 7. 1 mol. 8. 22 g. 9. 100 g. 10. 10%. 11. 0,250 L. 12. Lít.</p></details><table><thead><tr><th>Kết quả theo nhóm</th><th>Cách xử lý</th></tr></thead><tbody><tr><td>Đúng 2/2 và giải thích được</td><td>Tạm xem là vững; ôn lại sau.</td></tr><tr><td>Đúng 1/2</td><td>Ôn khái niệm và làm thêm 3 câu cơ bản.</td></tr><tr><td>Đúng 0/2</td><td>Học lại nhóm này trước khi học phần phụ thuộc phía sau.</td></tr></tbody></table></section>
<section><h2 id="sau-test">Sau bài test, bắt đầu ở đâu?</h2><p>Nếu sai nhóm A hoặc B, chưa nên lao vào bài toán mol. Nếu A–C đã vững nhưng sai D–F, tập trung đại lượng, công thức và đổi đơn vị. Sau 3–7 ngày, hãy làm câu tương đương chứ không học thuộc đúng bộ đáp án này.</p></section><section><h2>Kết luận</h2><p>Bài chẩn đoán chỉ hữu ích khi dẫn tới một quyết định học cụ thể. Hãy chọn nhóm sai sớm nhất, học một bài nền, luyện ít câu nhưng có chữa lỗi, rồi đo lại.</p></section>
</SeoArticle>}
